# Generated by Django 3.1.12 on 2025-09-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.CharField(max_length=100, null=True)),
                ('Review', models.CharField(max_length=225, null=True)),
                ('Sentiment', models.CharField(max_length=100, null=True)),
                ('Reviewer', models.EmailField(help_text='user_email', max_length=254)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
        migrations.CreateModel(
            name='LRM',
            fields=[
                ('S_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.FloatField()),
                ('Precision', models.FloatField()),
                ('F1_Score', models.FloatField()),
                ('Recall', models.FloatField()),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Logistic_Regression',
            },
        ),
        migrations.CreateModel(
            name='RFM',
            fields=[
                ('S_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.FloatField()),
                ('Precision', models.FloatField()),
                ('F1_Score', models.FloatField()),
                ('Recall', models.FloatField()),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Random_Forest',
            },
        ),
        migrations.CreateModel(
            name='UploadDatasetModel',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.FileField(upload_to='')),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'upload_dataset',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('user_email', models.EmailField(help_text='user_email', max_length=254, unique=True)),
                ('user_password', models.EmailField(help_text='user_password', max_length=50)),
                ('user_address', models.TextField(help_text='user_address', max_length=100)),
                ('user_contact', models.CharField(help_text='user_contact', max_length=15, null=True)),
                ('age', models.CharField(help_text='age', max_length=3, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('Otp_Num', models.IntegerField(null=True)),
                ('Otp_Status', models.TextField(default='pending', max_length=60, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
