# Generated by Django 3.1.12 on 2025-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADABOOST',
            fields=[
                ('S_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.FloatField()),
                ('Precision', models.FloatField()),
                ('F1_Score', models.FloatField()),
                ('Recall', models.FloatField()),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ADABoost',
            },
        ),
        migrations.CreateModel(
            name='DT',
            fields=[
                ('S_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.FloatField()),
                ('Precision', models.FloatField()),
                ('F1_Score', models.FloatField()),
                ('Recall', models.FloatField()),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Decision_Tree',
            },
        ),
        migrations.CreateModel(
            name='LGBM',
            fields=[
                ('S_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.FloatField()),
                ('Precision', models.FloatField()),
                ('F1_Score', models.FloatField()),
                ('Recall', models.FloatField()),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LGBM',
            },
        ),
        migrations.CreateModel(
            name='XGBOOST',
            fields=[
                ('S_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.FloatField()),
                ('Precision', models.FloatField()),
                ('F1_Score', models.FloatField()),
                ('Recall', models.FloatField()),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'XGBoost',
            },
        ),
    ]
