# Generated by Django 3.1.12 on 2025-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_adaboost_dt_lgbm_xgboost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANN',
            fields=[
                ('S_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.FloatField()),
                ('Precision', models.FloatField()),
                ('F1_Score', models.FloatField()),
                ('Recall', models.FloatField()),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ANN',
            },
        ),
    ]
